### ISSUE TITLE
Launch chatbot

### ISSUE THREAD

**Issue by patcon** [hyphacoop/hyphacoop-chatbot#1]
### To Do

- [x] create chatbot scaffold
- [x] add baseline scripts
- [x] create heroku app: https://hyphacoop-chatbot.herokuapp.com
  - [x] add to /inventory
  - [x] set up auto-deploy from master
    - [x] grant hyphacoop org access to heroku
  - [x] document deploy
- [x] create matrix user: `roobot:tomesh.net`
  - [x] add email and phone: hello@ / our org phone number
  - [x] add to /inventory
  - [x] add to /passwords
  - [x] invite user to `+hyphacoop:tomesh.net` community
  - [x] enable bot flair
- [x] create testing room: `#hyphacoop-bot-testing:tomesh.net`
  - [x] add room to `+hyphacoop:tomesh.net` community
- [x] ~~reset access token https://github.com/hyphacoop/organizing/issues/125~~ `migrated`
- [x] create archive command #2 
- [x] invite into private hypha room

**Comment by patcon** [comment]
@hyphacoop/infra-ops-wg open to gutchecks on all of this, possibly:
- using heroku
- allowing heroku app access to `hyphacoop` github org for auto-deploy

**Comment by dcwalk** [comment]
@patcon is there a hypha coop heroku group set up?

**Comment by patcon** [comment]
@dcwalk no, just this one app: https://hackmd.io/@patcon/HyH0W9bAE#Heroku

Heroku teams/groups lose ability to have free dyno hours, so I haven't found them useful.

I invited you to app, but we could also create a shared Heroku account to own these. (Needs a credit card attached at no cost to get full amount of free dyno hours.)

Or could just leave as-is, or something else. Any preferences/ideas?

**Comment by garrying** [comment]
@patcon this might be a post-launch thing to consider: migrating to hubot [v3](https://github.com/hubotio/hubot/releases)? I'm mostly thinking of not having to deal with CoffeeScript moving forward for custom scripts.

**Comment by patcon** [comment]
Ok! Thanks garry. You down to poof an issue for updating?

**Comment by patcon** [comment]
Thanks garry! created another issue to track: https://github.com/hyphacoop/hyphacoop-chatbot/issues/17

**Comment by patcon** [comment]
Ok, moved the final task into another issue where it fits better: https://github.com/hyphacoop/hyphacoop-chatbot/issues/4

Closing. thanks y'all!
